name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.State
author: KK964
api-version: 1.17
commands:
  state:
    description: State manager hub command
    permission: default